# Generated by Django 3.0 on 2019-12-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('event', models.CharField(max_length=50)),
                ('about_self', models.TextField()),
            ],
        ),
    ]
